version: '2'

services:
  devwarsztaty.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  devwarsztaty.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
