version: '2'

services:
  devwarsztaty.api:
    image: devwarsztaty.api
    build:
      context: ./DevWarsztaty.API
      dockerfile: Dockerfile

  devwarsztaty.service:
    image: devwarsztaty.service
    build:
      context: ./../DevWarsztaty.Service
      dockerfile: Dockerfile
